# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('server_cpu', models.IntegerField(default=100)),
                ('server_ram', models.IntegerField(default=100)),
                ('server_disk', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('machine_cpu', models.IntegerField(default=0)),
                ('machine_ram', models.IntegerField(default=0)),
                ('machine_disk', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='virtual_machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mamdaniAllocator.VirtualMachine'),
        ),
    ]
