# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamdaniAllocator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramusage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.IntegerField(max_length=100)),
                ('SMALL', models.IntegerField(default=0)),
                ('MEDIUM', models.IntegerField(default=0)),
                ('LARGE', models.IntegerField(default=0)),
            ],
        ),
    ]
