# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamdaniAllocator', '0005_diskset_ramset'),
    ]

    operations = [
        migrations.CreateModel(
            name='outputset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPTY', models.FloatField(default=0)),
                ('ALMOSTEMPTY', models.FloatField(default=0)),
                ('MEDIUM', models.FloatField(default=0)),
                ('ALMOSTFULL', models.FloatField(default=0)),
                ('FULL', models.FloatField(default=0)),
            ],
        ),
    ]
