# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamdaniAllocator', '0007_outputfunction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputfunction',
            name='ALMOSTEMPTY',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='outputfunction',
            name='ALMOSTFULL',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='outputfunction',
            name='EMPTY',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='outputfunction',
            name='FULL',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='outputfunction',
            name='MEDIUM',
            field=models.FloatField(default=0),
        ),
    ]
